language: node_js
dist: trusty
before_install:
  - sudo add-apt-repository ppa:coolwanglu/pdf2htmlex -y
  - sudo apt-get update -y
  - sudo apt-get install pdf2htmlex -y
node_js:
  - 8
  - 10
  - 12

